- import_tasks: role.yml
  tags:
    - consul_role
  when: >
        (consul_enabled is defined and
         consul_enabled|bool == True) or
        (uninstall_playbook is defined and
         uninstall_playbook|bool == True)
