---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Check ansible version >=2.6.5"
      assert:
        msg: "Ansible version 2.6.5 or above is required to run this playbook"
        that:
          - ansible_version.string is version("2.6.5", ">=")
      tags:
        - always
        - check_version
  vars:
    ansible_connection: local

- hosts: fullnode
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - iri
    - iotapm
    - monitoring
    - loadbalancer
    - nelson
