---
- hosts: fullnode
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - docker
    - iri
    - nginx
    - iotapm
    - monitoring
    - consul
    - haproxy
    - nelson
    - field
    - cleanup
