---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: "Check ansible version >=2.6.1"
      assert:
        msg: "Ansible version 2.6.1 or above is required to run this playbook"
        that:
          - ansible_version.string is version("2.6.1", ">=")
      tags:
        - always
        - check_version
      run_once: yes
      ignore_errors: "{{ ignore_assert_errors }}"
  vars:
    ansible_connection: local

- hosts: all
  gather_facts: true
  roles:
    - common

- hosts: fullnode
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - iri
    - iotapm
    - monitoring
    - loadbalancer
    - nelson
