- name: set variables centos/redhat
  set_fact:
    nodejs_bin: /usr/bin/node
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set variables debian/ubuntu
  set_fact:
    nodejs_bin: /usr/bin/nodejs
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: check nodejs minimum required version
  shell: "{{ nodejs_bin }} --version | grep -oh '^v{{ nodesource_version }}'"
  failed_when: false
  changed_when: false
  register: nodejs_version

- name: ensure npm removed
  yum:
    name: npm
    state: absent
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# Ubuntu
- name: get nodesource repo
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodesource_version }}.x | bash -"
  when: "nodejs_version.rc == 1 and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')"

# Centos
- name: get nodesource repo
  shell: "curl -sL https://rpm.nodesource.com/setup_{{ nodesource_version }}.x | bash -"
  when: "nodejs_version.rc == 1 and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')"

# Required
- name: Install epel-release
  yum:
    state: latest
    name: epel-release
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install some packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - make
      - gcc-c++
      - nodejs
      - firewalld
      - curl
      - lsof
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install some packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - make
      - g++
      - lsof
      - curl
      - nodejs
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Fix for ansible npm bug not upgrading package to latest
- name: upgrade nelson
  block:

    - name: Stop any active nelson service
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - nelson
        - nelson-gui

    - name: Remove current nelson packages
      npm:
        name: "{{ item }}"
        global: yes
        state: absent
      with_items:
        - nelson.cli
        - nelson.gui
        - '@semkodev/nelson.cli' 
        - '@semkodev/nelson.gui'
      notify:
        - restart nelson
        - restart nelson-gui

  when: upgrade_nelson is defined and upgrade_nelson|bool == true
  ignore_errors: yes
  tags:
    - nelson_npm

- name: Install nelson packages, this can take a while...
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  with_items:
    - serve
    - '@semkodev/nelson.cli'
  tags:
    - nelson_npm

# Using Ansible's npm module hangs when installing nelson.gui
- name: install nelson-gui via shell command
  shell: "npm install --unsafe-perm -g @semkodev/nelson.gui"
  tags:
    - nelson_npm
    - nelson_gui
  ignore_errors: yes
  register: nelson_gui_install

- name: install nelson-gui via shell command (retry)
  shell: "npm install --unsafe-perm -g @semkodev/nelson.gui@{{ nelson_gui_version }}"
  when: nelson_gui_install.rc != 0
  tags:
    - nelson_npm
    - nelson_gui
  ignore_errors: yes
