- name: stat iotapm config file to check if nginx installation from playbook
  stat:
    path: '/etc/nginx/conf.d/iotapm.conf'
  register: iotapm_file

- name: copy validation script
  copy:
    src: ../shared-files/validate_nginx_config.sh
    dest: /usr/local/bin/validate_nginx_config.sh
    mode: 0755
  when: install_nginx is defined and install_nginx

- set_fact:
    nginx_installed: True
  when:
    - iotapm_file.stat.exists == True

- name: copy ssl.cfg nginx config
  template:
    src: ../shared-files/ssl.cfg.j2
    dest: /etc/nginx/conf.d/ssl.cfg
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d conf.d/ssl.conf -r"
  notify:
    - reload nginx

- name: copy nelson-gui nginx conf file
  template:
    src: templates/nelson-gui.conf.j2
    dest: /etc/nginx/conf.d/nelson-gui.conf
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d conf.d/nelson-gui.conf -r"
  notify:
    - reload nginx
