- name: Install some packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - openssl-devel
      - zlib-devel
      - pcre-devel
      - gcc
      - gcc-c++
      - kernel-devel
      - readline-devel
      - ncurses-devel
