- name: Install some packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - whois
      - libssl-dev
      - zlib1g-dev
      - libpcre3-dev
      - build-essential
      - libreadline-dev
