prom_version: 2.0.0
prom_username: prometheus
prom_basedir: /opt/prometheus
prom_datadir: /var/lib/prometheus
prom_configdir: /etc/prometheus
prom_config: prometheus.yaml
prom_port: 9090
prom_bind_address: 127.0.0.1
prom_proxy_port: 8999

exporter_version: 0.15.2
exporter_basedir: /opt/prometheus/node_exporter
exporter_port: 9100
exporter_bind_address: 127.0.0.1

iota_prom_exporter_image: bambash/iota-prom-exporter
iota_prom_exporter_tag: latest
iota_prom_exporter_basedir: /var/lib/iota-prom-exporter
iota_prom_exporter_port: 9311
iota_prom_exporter_bind: 127.0.0.1
iota_prom_exporter_market_data: true
iota_prom_exporter_db_days_retention: 14

field_exporter_bind_port: 9337
field_exporter_bind_address: 127.0.0.1
# Here path provided and full path constructed in task
field_exporter_basedir: /var/lib/field_exporter

# Here (legacy) has been provided the full path
alertmanager_basedir: /opt/prometheus/alertmanager
alertmanager_version: 0.12.0
alertmanager_port: 9093
alertmanager_proxy_port: 9993
alertmanager_bind: 127.0.0.1
alertmanager_email_from: alertmanager
alertmanager_email_to: root@localhost
alertmanager_loglevel: info
smtp_host: localhost
smtp_port: 25

prom_am_executor_port: 9158
