- name: copy grafana new config file
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    backup: yes
  notify:
    - restart grafana

- name: start and enable grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: flush handlers
  meta: flush_handlers

- name: Wait max 90 seconds for grafana port to become available
  wait_for:
    timeout: 90
    port: "{{ grafana_port }}"

- name: create provisioning, datasources and dashboards directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ grafana_provisioning_path }}"
    - "{{ grafana_provisioning_path }}/datasources"
    - "{{ grafana_provisioning_path }}/dashboards"
    - "{{ grafana_dashboards_path }}"

- name: copy default datasource provisioning file
  template:
    src: templates/grafana.datasources.prov.yaml.j2
    dest: "{{ grafana_provisioning_path }}/datasources/grafana.datasources.prov.yaml"
  notify:
    - restart grafana

- name: copy default dashboard provisioning file
  template:
    src: templates/grafana.dashboards.prov.yaml.j2
    dest: "{{ grafana_provisioning_path }}/dashboards/grafana.dashboards.prov.yaml"
  notify:
    - restart grafana

- name: copy dashboards
  copy:
    src: "files/{{ item }}"
    dest: "{{ grafana_dashboards_path }}/{{ item }}"
  with_items:
    - "iota_exporter_dashboard.json"
    - "prometheus_dashboard.json"
    - "node_exporter_dashboard.json"

- name: copy field-exporter dashboard
  copy:
    src: "{{ field_exporter_fulldir }}/dashboards/field_exporter_dashboard_grafana.json"
    dest: "{{ grafana_dashboards_path }}/field_exporter_dashboard.json"
  when: >
        field_enabled is defined and
        field_enabled|bool == true
  tags:
    - field_exporter
