- import_tasks: deps.yml
  tags:
    - monitoring_deps

- import_tasks: firewall.yml
  tags:
    - monitoring_firewall

- import_tasks: prometheus.yml
  tags:
    - prometheus_config

- import_tasks: alertmanager.yml
  tags:
    - alertmanager_config

- import_tasks: node_exporter.yml
  tags:
    - node_exporter_config

- import_tasks: iota-prom-exporter.yml
  tags:
    - iota_prom_exporter

- import_tasks: grafana.yml
  tags:
    - grafana_config

- import_tasks: prom-am-executor.yml
  tags:
    - prom_am_executor

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_monitoring
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
