- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - nbctl_config

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: stop grafana
  systemd:
    name: grafana-server
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove yum grafana
  block:

    - name: uninstall grafana
      yum:
        name: grafana
        state: absent

    - name: remove grafana repository
      yum_repository:
        name: grafana
        description: grafana
        baseurl: https://packagecloud.io/grafana/stable/el/6/$basearch
        state: absent

  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: remove apt grafana 
  block:

    - name: uninstall grafana
      apt:
        state: absent
        name: grafana

    - name: remove grafana apt repository
      apt_repository:
        repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
        state: absent

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: remove nginx ports in firewall for monitoring services
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: disabled
    immediate: yes
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: remove prometheus grafana nginx port via selinux seport
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: absent
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: remove prometheus and grafana nginx port from firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ item }}"
    delete: yes
  with_items:
    - "{{ prom_nginx_port }}"
    - "{{ grafana_nginx_port }}"
    - "{{ alertmanager_nginx_port }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: stop monitoring services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: yes
  with_items:
    - prometheus
    - alertmanager
    - iota-prom-exporter
    - prom-am-executor
    - node-exporter

- name: remove monitoring service files
  file:
    path: "{{ item }}"
    state: absent
  notify:
    - reload systemd
  with_items:
    - '/etc/systemd/system/prometheus.service'
    - '/etc/systemd/system/node-exporter.service'
    - '/etc/systemd/system/alertmanager.service'
    - '/etc/systemd/system/prom-am-executor.service'
    - '/etc/systemd/system/iota-prom-exporter.service'

- name: remove monitoring related files and paths
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ prom_basedir }}"
    - "{{ prom_datadir}}"
    - "{{ prom_configdir }}"
    - '/etc/rsyslog.d/node_exporter.conf'
    - '/etc/nginx/conf.d/alertmanager.conf'
    - '/etc/nginx/conf.d/prometheus.conf'
    - '/etc/nginx/conf.d/grafana.conf'

- name: remove provisioning, datasources and dashboards directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ grafana_provisioning_path }}"
    - "{{ grafana_dashboards_path }}"

- name: remove prometheus user
  user:
    name: "{{ prom_username }}"
    state: absent
