- name: Install some packages
  yum: state=latest name={{ item }}
  with_items:
    - make
    - gcc-c++
    - nodejs
    - firewalld
    - curl
    - lsof
    - python-passlib
    - httpd-tools
    - python-pip
  when: ansible_distribution == 'CentOS' 

- name: Install some packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - make
    - g++
    - lsof
    - curl
    - python-passlib
    - apache2-utils
    - python-pip
    - python3-pip
  when: ansible_distribution == 'Ubuntu'

- name: install pip requirements, to support remote installations
  pip:
    name: passlib
